# Generated by Django 5.2.4 on 2025-07-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mobile_money_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='mobile_money_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Mobile number for mobile money payments', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('credit_card', 'Credit Card'), ('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money')], default='paypal', max_length=20),
        ),
    ]
